import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ReactQueryProvider } from '@/lib/react-query-provider'
import '@/lib/sentry.client'
import { ThemeProvider } from '@/lib/theme-provider'
import { LayoutClient } from '@/components/common/LayoutClient'
import { ToastProvider } from '@/components/ui/Toast'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ko">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ThemeProvider>
					<ReactQueryProvider>
						<ToastProvider>
							<LayoutClient>{children}</LayoutClient>
						</ToastProvider>
					</ReactQueryProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
