import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ReactQueryProvider } from '@/lib/react-query-provider'
import '@/lib/sentry.client'
import { ThemeProvider } from '@/lib/theme-provider'
import { Header } from '@/components/common/Header'
import { Footer } from '@/components/common/Footer'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ThemeProvider>
					<ReactQueryProvider>
						<Header />
						<main className="mx-auto max-w-6xl px-4 py-6">{children}</main>
						<Footer />
					</ReactQueryProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
